global:
  env: review
frontend:
  app: blockscout
  enabled: true
  image:
    _default: ghcr.io/blockscout/frontend:main
  ingress:
    enabled: true
    host:
      _default: frontend.test.blockscout.aws-k8s.blockscout.com
    # enable https
    tls:
      enabled: true
    path:
      exact:
        # - "/(apps|auth/profile|account)"
        - "/"
      prefix:
        # - "/(apps|auth/profile|account)"
        - "/_next"
        - "/node-api"
        - "/account"
        - "/apps"
        - "/static"
        - "/auth/profile"
        - "/txs"
        - "/tx"
        - "/blocks"
        - "/block"
        - "/login"
        - "/address"
        - "/stats"
        - "/search-results"
        - "/token"
        - "/tokens"
        - "/accounts"
        - "/visualize"
        - "/api-docs"
        - "/csv-export"
        - "/verified-contracts"
        - "/graphiql"
        - "/l2-output-roots"
        - "/l2-txn-batches"
        - "/l2-withdrawals"
        - "/l2-deposits"

  resources:
    limits:
      memory:
        _default: 768Mi
      cpu:
        _default: "1"
    requests:
      memory:
        _default: 384Mi
      cpu:
        _default: 250m
  environment:
    NEXT_PUBLIC_BLOCKSCOUT_VERSION:
      _default: v5.1.0-beta
    NEXT_PUBLIC_FOOTER_GITHUB_LINK:
      _default: https://github.com/blockscout/blockscout
    NEXT_PUBLIC_FOOTER_TWITTER_LINK:
      _default: https://www.twitter.com/blockscoutcom
    NEXT_PUBLIC_APP_ENV:
      _default: preview
    NEXT_PUBLIC_APP_INSTANCE:
      _default: base_goerli
    NEXT_PUBLIC_NETWORK_NAME:
      _default: "Base GÃ¶erli"
    NEXT_PUBLIC_NETWORK_SHORT_NAME:
      _default: Base
    NEXT_PUBLIC_NETWORK_ASSETS_PATHNAME:
      _default: optimism
    NEXT_PUBLIC_NETWORK_ID:
      _default: 420
    NEXT_PUBLIC_NETWORK_CURRENCY_NAME:
      _default: Ether
    NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL:
      _default: ETH
    NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS:
      _default: 18
    NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE:
      _default: validation
    NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED:
      _default: 'true'
    NEXT_PUBLIC_NETWORK_LOGO:
      _default: https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-logos/base.svg
    NEXT_PUBLIC_NETWORK_ICON:
      _default: https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-icons/base.svg
    NEXT_PUBLIC_FEATURED_NETWORKS:
      _default: https://raw.githubusercontent.com/blockscout/frontend-configs/dev/configs/featured-networks/base-goerli.json
    NEXT_PUBLIC_API_HOST:
      _default: blockscout-optimism-goerli.test.aws-k8s.blockscout.com
      review: blockscout-optimism-goerli.test.aws-k8s.blockscout.com
    NEXT_PUBLIC_APP_HOST:
      _default: blockscout-optimism-goerli.test.aws-k8s.blockscout.com
    NEXT_PUBLIC_API_BASE_PATH:
      _default: /
    NEXT_PUBLIC_MARKETPLACE_SUBMIT_FORM:
      _default: https://airtable.com/shrqUAcjgGJ4jU88C
    NEXT_PUBLIC_LOGOUT_URL:
      _default: https://blockscoutcom.us.auth0.com/v2/logout
    NEXT_PUBLIC_LOGOUT_RETURN_URL:
      _default: http://blockscout-optimism-goerli.test.aws-k8s.blockscout.com/auth/logout
      review: http://blockscout-optimism-goerli.test.aws-k8s.blockscout.com/auth/logout
    NEXT_PUBLIC_STATS_API_HOST:
      _default: https://stats-optimism-goerli.test.aws-k8s.blockscout.com
    NEXT_PUBLIC_API_SPEC_URL:
      _default: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml
    NEXT_PUBLIC_MARKETPLACE_CONFIG_URL:
      _default: https://raw.githubusercontent.com/blockscout/frontend-configs/dev/configs/marketplace/base-goerli.json
    NEXT_PUBLIC_NETWORK_EXPLORERS:
      _default: ''
    NEXT_PUBLIC_HOMEPAGE_PLATE_GRADIENT:
      _default: "linear-gradient(136.9deg,rgb(107 94 236) 1.5%,rgb(0 82 255) 56.84%,rgb(82 62 231) 98.54%)"
    NEXT_PUBLIC_NETWORK_TOKEN_ADDRESS:
      _default: ''
    NEXT_PUBLIC_NETWORK_RPC_URL:
      _default: https://goerli.optimism.io
    NEXT_PUBLIC_WEB3_DEFAULT_WALLET:
      _default: coinbase
    NEXT_PUBLIC_WEB3_DISABLE_ADD_TOKEN_TO_WALLET:
      _default: true
    NEXT_PUBLIC_HOMEPAGE_CHARTS:
      _default: "['daily_txs']"
    NEXT_PUBLIC_IS_TESTNET:
      _default: "true"
    NEXT_PUBLIC_VISUALIZE_API_HOST:
      _default: https://visualizer-optimism-goerli.test.aws-k8s.blockscout.com
    NEXT_PUBLIC_CONTRACT_INFO_API_HOST:
      _default: https://contracts-info-test.k8s-dev.blockscout.com
    NEXT_PUBLIC_ADMIN_SERVICE_API_HOST:
      _default: https://admin-rs-test.k8s-dev.blockscout.com
    NEXT_PUBLIC_IS_L2_NETWORK:
      _default: "true"
    NEXT_PUBLIC_L1_BASE_URL:
      _default: https://blockscout-main.test.aws-k8s.blockscout.com
    NEXT_PUBLIC_L2_WITHDRAWAL_URL:
      _default: https://app.optimism.io/bridge/withdraw
    NEXT_PUBLIC_GRAPHIQL_TRANSACTION:
      _default: 0x4a0ed8ddf751a7cb5297f827699117b0f6d21a0b2907594d300dc9fed75c7e62
