blockscout:
    environment:
        INDEXER_OPTIMISM_L1_RPC:
            _default: ENC[AES256_GCM,data:a02FoR3U/KlxsFVFiSGSLdFOFIDwS5eBgw==,iv:rmT8bVh3xyqKeebtnT+/eIC0bSGWKZhJ9H52cUsqFxM=,tag:OsRo1D2DtfMIgCGjAvqobw==,type:str]
        ACCOUNT_USERNAME:
            _default: ENC[AES256_GCM,data:n9Wc7xjBFdWHJNaKBwpVVykz3FbBtqicKdf6yD/kMLKuts/0Rv8vfQ20gSahIvSbbno=,iv:FRyRAwelWF1PHqbIJX09MH+VVqW53luYraLYq/A21j4=,tag:YUejqoXCZjWNUhRZ9emd+g==,type:str]
        ACCOUNT_PASSWORD:
            _default: ENC[AES256_GCM,data:JVEI0zxaV0pNe74DDB75gt0=,iv:v05W/HN2vzF85yuYWjJYDm1IWgYd2UdeMEnXgfVbYfo=,tag:+8afW2VG1z8ke78vM4N+Lw==,type:str]
        MAILSLURP_API_KEY:
            _default: ENC[AES256_GCM,data:8RffJ77fEUMK41bBeFbJDaqvvbVgtoSKbVItKkWl3TaV7V605qQLdRPPo9pc4wpWDYtMDPZ7du9rjjr8R16jpg==,iv:voau83nNEXZN65F/ZEno0TOEToCEHBNt7tiAFigIqlI=,tag:Q9Ozhcnz32aNmYiVg3c6Rw==,type:str]
        MAILSLURP_EMAIL_ID:
            _default: ENC[AES256_GCM,data:xTJjX9TJvcWNHGtlIPrsyI1FrQfTx5mz/ImA2PQjPWzo59q5,iv:mhu9H73Dg6q8aYhPU7+ly5HGJddUmLi3AuoAWePbvtc=,tag:wyi0Y7FH8zTwjtft5nAsLg==,type:str]
        ACCOUNT_AUTH0_DOMAIN:
            _default: ENC[AES256_GCM,data:dhZF85GiypKiyY3TBIuZfNhtTk+qMU0Kz9k=,iv:kEfANVJvafgxvjR7tYQc1S5JUJVfULPJJCKovBeBGgI=,tag:3Ct3Fe3Z3ptMTEnJyr7Ikg==,type:str]
        ACCOUNT_AUTH0_CLIENT_ID:
            _default: ENC[AES256_GCM,data:prh45OKeStfh+hPRZLvN981E+yPjjN1E0cI2uIMT+28=,iv:/ZrYd29B2LUZn2s55w/tWmDURDvQwdIDl8JZl8dQhxY=,tag:n2S7OYoag+kI3rNrnmSlTg==,type:str]
        ACCOUNT_AUTH0_CLIENT_SECRET:
            _default: ENC[AES256_GCM,data:bgP4VwZ91eMzJVQ3/+fkqNCwBIAv3P12qRoGWu9QkfCKpj3e+Dwt1qjsYV1iNkcjQAJx3jOpVGlsbgdcBGFzHw==,iv:gpa6tbkxHv56wwI3Owdnr5MArJYdiVO3A0UMOsrgCls=,tag:CIgupR1ZNjsVtFYVG2OtHA==,type:str]
        ACCOUNT_AUTH0_CALLBACK_URL:
            _default: ENC[AES256_GCM,data:+EoMWtXdJA5DnRprCaps38VbQlLcJikKvB7FA0VMhaw+aq1d/rh5yIxl/CQBIo2eO8EESoVz6eUjzvgchbmv2IaiGgG3DnZx,iv:nfPmwEZMXM2SOIZ3OMr5u7GTbX6ni5VuFpn5SyHKMfE=,tag:4ePZ5NZ+rdBZf8xWDfEbzA==,type:str]
        ACCOUNT_SENDGRID_API_KEY:
            _default: ENC[AES256_GCM,data:i08k9qiHA/31nyAri5pIm8MqCUZXLWjvQgcYpAyrcsToszt/L+QsYVcdCEerI0udtd2gJvLuRz3k8GcpZ9OfQB2Y0kJn,iv:Pt3rg7GjhfDw5S4VV9HpLSDsO4AhXlGIsNhdc5rYqCQ=,tag:zL/bLVgSS41kgnv69GxLMg==,type:str]
        ACCOUNT_SENDGRID_SENDER:
            _default: ENC[AES256_GCM,data:jnaN7XRQnjAJ1oOcswIBiBE8ZWqT4Q==,iv:WJHNTmwzE5FgZcu8hqoSiwWjYlr9fARW0nZY+ci/2eI=,tag:Ks+yhmJCA9hscHUYk3e+9g==,type:str]
        ACCOUNT_SENDGRID_TEMPLATE:
            _default: ENC[AES256_GCM,data:26r5ti5xVwlf5Fr4vtNxmk1mYxg5DjcI9IO12WSI8dIlcA==,iv:hc9YA3Y0Lney3/+fpTeVEX0GuuxdhNJFpd4B30mGHOc=,tag:8k/GfGHzdylAwTs0QWFXQg==,type:str]
        ACCOUNT_PUBLIC_TAGS_AIRTABLE_URL:
            _default: ENC[AES256_GCM,data:b/+BmS5vj6rtKGFHdODTiMGAU05WG0MTT9rQtFXLkKPL+zv4ehKRB9vDa/FwlTNldkOFooIdDfys2H4fuKw=,iv:PvMXWccd47dZNdSWMnrSZceSTcgRNLelCB3F/UjcSkU=,tag:iwwRZrEUqyR5B84iUh5vkQ==,type:str]
        ACCOUNT_PUBLIC_TAGS_AIRTABLE_API_KEY:
            _default: ENC[AES256_GCM,data:gcokN6uXa09j6+rUFmsoeU8=,iv:XBb1yrO9ZeiOzMue2cPX6C6BeCJB/dZ2TAmKoVxMOrY=,tag:BkVfU9quPOppPagx8Gr/5Q==,type:str]
        ACCOUNT_CLOAK_KEY:
            _default: ENC[AES256_GCM,data:kmbDlujc+JB7VNsMEwnlTXIC9zuN0smaYKYvmfMCVk484qe+1fbmhgeW0rM=,iv:b/sPf2xfGJgMgDL4UIF7K5iFuKJD3XfLIUI86E/Ltno=,tag:/lJj8VKQlYeDpsGYbqkVAg==,type:str]
        SECRET_KEY_BASE:
            _default: ENC[AES256_GCM,data:pojKRWQIlKeiqpGxEPe0p3n2VGe5zgBMvowU5jZzNofnoRXtgXPKdFpsWNPVzYtxFUOliNt5YmuIoQfobE1eaWqk2HVmQkvluSsJZuodkipFvc5bo5P1wzJGeOJ/hd+7dxYsdjKhqpWU1+OETpEy9VTxNCU8DzaIWPCddrS4Kt4=,iv:U7eTYtpNFcqXDbvGHX+P2WnQWhzBKMO3xZBiZVLXN4w=,tag:j0nNFBZhOBbI87bA8XjizQ==,type:str]
        DATABASE_URL:
            _default: ENC[AES256_GCM,data:9MKvBnelyJTdRBUuwL5oqmyBB4fphgYnQdKTzdL12gpNbDBdZTDVTeU/RHyL2rcuaHKLN6yEG10N6MZ4dEXAciQ=,iv:Uj3KA7kyRETJmW3LK41ziJsIpuq50PcggH7wDDOCSIw=,tag:gUswuDk7AefQerkqoRpKPg==,type:str]
        ACCOUNT_DATABASE_URL:
            _default: ENC[AES256_GCM,data:b6ZuCyEkINzvv2osvlQP8iTh4fwoivVCPOEKy5QRHs0cbVW4f3bp//HATPuAhD2T3MA/OSyqv5Xh6DpRjKPBV68=,iv:Yon9UJXtBmAXUX/G7BSKsbCT64eqM0nJ3AiMvgTxeRM=,tag:jWb4JgTI4b/bEbhgTuPBXg==,type:str]
        ACCOUNT_REDIS_URL:
            _default: ENC[AES256_GCM,data:a+lfkUrRstKt8sc/SqlDqr2d0iub9hy3ttzLklGirIuakYay5druY5Yma8WA5fy/E/LgsP0xTIbE2Xvd23L33tpOWeh1KuLsiM0W+D6NIInf,iv:s3mMrzKfw0OMsYScu1xaqfK6uTgR/Pp57FR+nvuK1lA=,tag:nkk22fDDQEr7UIKfCxTtHA==,type:str]
        ETHEREUM_JSONRPC_TRACE_URL:
            _default: ENC[AES256_GCM,data:pR5THHyrb1H439lYmyxB5Ihwovsz+fgiRg==,iv:fDw/ltYBebfeaFhnyUV+RjAHPSskGOzQxMCD0ccu3LM=,tag:dn3a7E/CT9f1iEmRI+m19w==,type:str]
        ETHEREUM_JSONRPC_HTTP_URL:
            _default: ENC[AES256_GCM,data:5k4ecTp3DsHduR2y/5fFdUzRJ6YHRqJPVA==,iv:cj73TBdG438t/PFv+MY3ht0AoxphTaZxM/JSHUr5MB0=,tag:jo/Tq1iGOj/bBLA4+c4pXA==,type:str]
        ETHEREUM_JSONRPC_WS_URL:
            _default: ENC[AES256_GCM,data:dfKCFydZYOovhjVx5ZCEw/lyeZvkutM=,iv:lBvz6wABX33tMYBzcdu5xcCcvs+WNXsToPfzyoKra7w=,tag:0zGDybcPVlxxcZTKfCk47A==,type:str]
        RE_CAPTCHA_SECRET_KEY:
            _default: ENC[AES256_GCM,data:fHIsaJQY6YrvoJKFDFZlBuunFD6QKYdUUOoW+aLV/44VCsWhrXbMUQ==,iv:teJEbP6pVC4WHeJwptf/DfRbp5Y8x/0OExTfClfLPyU=,tag:5nkNFZcJEFg5v0br2JUpnA==,type:str]
        RE_CAPTCHA_CLIENT_KEY:
            _default: ENC[AES256_GCM,data:ROEBG5XrOwAofN2ZnFnwekuqvHjDFu1Dp5V20Ud9gvqV1xc324InYA==,iv:EubA1HilDAtNaqdpTbFWaWSAf8kCiWgStada1dKpOD8=,tag:ry4796qJAekQKlz4sWGQKQ==,type:str]
scVerifier:
    environment:
        SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__ACCESS_KEY:
            _default: ENC[AES256_GCM,data:MCvrmnSbcTshllJJDHavMJ8wEqqJL0sf,iv:VWWulTsz7JQ4YyOjbZL6atf6ccy/hDdqL6CfaOuR1t4=,tag:Q/z+oJcW+xkNOZBPQnHZ6A==,type:str]
        SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__SECRET_KEY:
            _default: ENC[AES256_GCM,data:tQ4pv08lOAX32MyXPcRoSs1FP8weByPIlqODDxbT0mVPAvIJtlnIWQ==,iv:GdSdPRRVNMPPmgP+6/hIs+f7EAB5YIrgPsNMLFPSueQ=,tag:borgqBxHa4zM3hC1kZKnIg==,type:str]
        SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__BUCKET:
            _default: ENC[AES256_GCM,data:p89bs0/NjUsmQ8ms/A==,iv:W/gXfPIAajBlK2KGn2NLaTyYwgQixbTtLjZKdL02ZI0=,tag:HaIqLb9suYmB5fJI1/Ghsg==,type:str]
postgres:
    environment:
        POSTGRES_PASSWORD:
            _default: ENC[AES256_GCM,data:sL3yuVfpyRw=,iv:Dx+UOVcVaPjyeXaIMMEMRJC32L50R8TPK3iwR/APmJs=,tag:DSAw2Q45skw0pvctx1gPBQ==,type:str]
        POSTGRES_DB:
            _default: ENC[AES256_GCM,data:AeTupGw/FWZTMA==,iv:hMwGd/ctSD2gzDEfQ9dNb0XjAO2IBhhV+47meWDhQio=,tag:qF169hU9fjQ5J7pjtJSgYw==,type:str]
geth:
    files:
        list:
            genesis.json: ENC[AES256_GCM,data:52IK/W78eh0vT1APmAXroNL8iHTR/1ojT7ZizAHD1Tdrcg8Gw/xdD9P9Ow2WqZEoLgkMbokOU5ESVMJTQatwSKm3lP83i0wKx7JIQ+JtxyyR3XyY3rblTY3R4v5f+ckiqRYDstzdMnt4XhOQAm6Q07JlN97spwdplNtWFPqTzIEv5/zF6AqDmUcgKT3cKqbafo5ahVOHPg/lt2LrsvuSGM/ENlq3OE6Z9JmZG7nKVrMRkqEleVcb8SLeOFRv+7rSiGhJ6Se1818I4dnWjQCx/KTLpiZJtwZmz2Vurrk2AskcN91P0SK8cDWiR2oR3OP2dke05luhB7EBHHkEXb/62FAhOk0wtBWEkVWSWDMSaPA2fhCciw3d+A/RM0iV9krzw4n4+WyPhSt43a0gVovSxRUkxfJGGqZj5GRT9j8E8bRLi9ZBdGbkGbEUmbv8cgYpMooBTj6rlzPHGP2kv7yJ4NngY6APws6NkIIK0OkHAsP1HFTF07Up5FEtFkUG9Tqr18RU62GnkWPyXvB0aFAHf60mCDkPGove4IPO74xOGUS2cMHxFR7NFo5lyzVwN1ndvkTpxh4JE2v7Nenn65etZq6vbX5O6xBrCBquM9XjZqRaolX0pdYOG8/jdrjNd2EyNimYFDjJ5VejjZV0Un/Z7vO+SHzKpiy+EaWAUNoIix7/XGk0/oL9n3B290t+9EmpqTAu/7CS5E5pq2F6wuDLqpkIZoW2Gxyg3qm7c9xPB2Wl9e6xG3Am8gsQZQ7wVSrmNIgmEFvTI2TufN/5OCxTOJhvoAkuA3EJvpWU9EsjmYAqy8uHa0gu4J+WN17yh2uMeMDKDg2vvekn+FYP0SrpFkBcQ4W2InTQF0BVmwIlrta6wBDVcKT37XxLGpV5C6W5HzMOQ/fnHnEauO4YY8HMvqtyV4wCbibbaM24/NvcYA9EeOKNmLAart4ZVK74jgZyFQVM0mTXm+uU0u8jLXuEAQt+vVSywuQr8Qa7VsWMjegW7+O5zPNJmv7AsB3eQz8kXTLGy4+BQ7PzXMnnuv1krDk70vK7e46oIj7Kmnguf+MQKHlmV+PXBbqjLeSdlfk+oUpoSCikWiPI1fBR41AY0DBgO68qb7b992ezpC25MSI69NX1/JYl/VDoO+2n6WrSUqDYHjQ7xbq+7n4QB3RiavQyASTeXNsNyxIlR+ZsZC29fZlssQKyY1653zVYwUVpBxUAuHX2ytqEMzUoodCFf3sXA4lUGJMEgq6/rsSpVwBt2xB83yWFCFQm/hJRqy3ZCmlk4DYVd/MVc/t2ODvQdg==,iv:HEVGR7XavGkCVRQs/ytln2gn5IIu4x42jeAhK8mAc00=,tag:7DcGtafYe2/qfpAUgqO3Xg==,type:str]
            init.sh: ENC[AES256_GCM,data:cjFeSh57rgxDBxEYmMTLzIze//1jpqZuD2F9GAz4bapY0ykJS5VljH6Z62wfYM80Nhvy07xkQN1nuu5UHAdissr4QSFokpKZjCzbz+venbw/ug4dL0NDE8h2X6o3ciQJPe8jC6Ei+blRqkpiXEiDh6GDhOWNpCn6gLcAJPtePg/KiS/KAFm3PnOgjf+iGacuv4J2kzALlin9D6QQYsNyYHhjTH9YrBZZguAvPKdgQGGM3OniaJxx4FcET8aMjIrzVhD4ESwm/rFpKBF11HM1JysIjKOFDS65Z1sm62gdtk6iV6pEthr3Db2XJQL/BBPeL9VHUnLsC6GgZOvxML0rJcyO9yBlhwbtR65EymkSdacB5NXVzCig8Fb2IMhAHmGyEiFnFMBqOgUPwug95VfqTCwEvaxrEbOsGk5j/8w1ZkwTVE9OqlQziCM4gBrASxTRuclCVGazU1GQ4UiJb6i0bjDOP3/78h5PpmbO8NSGvU8IJCIik8G1UIsMpAsmTD8DbUC3ui5JC1VA9v4lu0r7awPOiaW/0anZkoE2FxJK/NsnrODTLXNlYcg7/STCHHSlwoev4E0ANMidGtTv+pamH40KtMxF4PlVbRJbG+FKQMOVuO5R4MJje3EteEyU4ph6hgZD6V1rYpG8iJNkF4RrCr6ZkfUbdp9mgAgiFNtINTyt0Uc868AGUHpRyre9y4fmf88p6IcF/oO1lyF3WeQf4D9zRShbUwnrx0ryPGtgz2idVuPOOJKUGYY9sQ==,iv:c7YKsFJsuMQjBOdyrUWHBD9s7S2lzuHi96Wt+52J4kc=,tag:hR2Y6CsWqCLyQRhKJFTe8A==,type:str]
            password.txt: ""
frontend:
    environment:
        NEXT_PUBLIC_NETWORK_TOKEN_ADDRESS:
            _default: ENC[AES256_GCM,data:iDjScwB2WgiYgk0xQZRlvL7/+TcdvHfdpx361OKX+cuJaNo5Mmlge73S,iv:JI66Yl+fJC8QiRaKcLzLwYo2O+chqWGZOhmzIVF1gfM=,tag:g+6pI9D1xnoAt57DdNAJMQ==,type:str]
        NEXT_PUBLIC_AUTH0_CLIENT_ID:
            _default: ENC[AES256_GCM,data:j45ae8bg6TtnePS5BvABQRxUOwqQhHHRkldqLxBUGcc=,iv:oX+aAz+TWvyRgRnWhWDGlYVLblSl8REET3r0CCY9QUw=,tag:dZo6HxAgJPOc8EL3uuGIPw==,type:str]
        NEXT_PUBLIC_GOOGLE_ANALYTICS_PROPERTY_ID:
            _default: ENC[AES256_GCM,data:0iJ0Vdw4Nj07k7tRGXk=,iv:R9LFat+nfrYE6AJXoRerewfn6M7jdv2rWU4EWiSwTsA=,tag:hZKDpmBNAA+hNg792Gl1Jw==,type:str]
stats:
    environment:
        STATS__DB_URL:
            _default: ENC[AES256_GCM,data:2bJ3ZiRPwRcM7l8ekR0g3aiFNa7LujTCsBCIdBCrb6bEFWAET40EKX8LMgC3vyzdiAM=,iv:hyf2vkUhMlCxSHvvMWfrv53KAvInuRAjO2i/wMtx9b4=,tag:18WPm0Q79dF99ltQZH5JoA==,type:str]
        STATS__BLOCKSCOUT_DB_URL:
            _default: ENC[AES256_GCM,data:LA3a1Wjw1A4HNJyniXK/eIW+imtcoHasWtczn8WpugATFmm68SgDYM47eviHIySb/AJOBFX1Gph1/cLL3CDcCw4=,iv:YUSlq0mP1TMI8Z8jwmyltUkYVYEU0i1cvk9vavIq48Y=,tag:4TM7dof1nzYvDV16aFaPwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-27T16:27:47Z"
    mac: ENC[AES256_GCM,data:TUIxPt/HMLzkWlPdBcM2mKGlNU+6ob+EWvtfKWAHZaVhH2qwoi+HI+Ncx+j3H9/MR6q9Uhhr611s8rCF0LdwbsK+LGdOBBql+45vfmCE1XRl/DS0LFdZxkZn4ub49C9Uf8g0DOVt02NJQNh3ZNaBa+l2nIirh643hLvzFCCqBM8=,iv:tqRFfzSk0W+NzEADzIWy08aUnpJgcIPBHhUhM0Kf+VA=,tag:0IiapCTs0UITa38cwVyZqQ==,type:str]
    pgp:
        - created_at: "2022-09-22T09:52:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1MXzg1c4SMLAQf/WD1CUDjWm2YTR58vg+T8WwLdFWpmLdqRlJVnKCPg0E13
            dJXaLmNf2wVLFfVJg3pVpIT9LXphER+y+85ZTm6GUA0HZz8UrklfuIL1xprptcHY
            ocLPI7Jq6zbOEfakHlQX6AdA6Nl2DxZGSb0QWjjkC5UX9PfeTYQheHToiRwWEX2A
            RrSm2yxzM6SXjUw6/895Il9lWzyJPbBp2EIeOqr2RkobPWRHJox7Sm0Mi91VXWMH
            P8lQZjMBOE9n72IYjFydMQume8ScSB7lPiZ09xwoZzuXKNsR23IG6bGyRtlRbCxd
            IcKV00fgMrHdBBsyND9MWLwgEGqxp4YZbbPOFOGNP9JcAYTNI81+c/1BA3VWtg+N
            BTEI2wP8/HXD9sfl7tVx0Lh/o48vIxe3Lu/obZaqaRn/HcYgXTqvUezEkna5gxs9
            n+sKHNBJnKLcNrF6WRahhOYApGff/aabgxlG1Ec=
            =m714
            -----END PGP MESSAGE-----
          fp: 99E83B7490B1A9F51781E6055317CE0D5CE1230B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
