name: Cleanup environments

on:
  pull_request:
    types:
      - closed
      - merged
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  cleanup_release:
    uses: blockscout/actions/.github/workflows/cleanup_helmfile.yaml@main
    with:
      appName: review-l2-$GITHUB_REF_NAME_SLUG
      globalEnv: review
      helmfileDir: deploy
      kubeConfigSecret: ci/data/dev/kubeconfig/k8s-dev
      vaultRole: ci-dev
    secrets: inherit
  cleanup_l2_release:
    uses: blockscout/actions/.github/workflows/cleanup_helmfile.yaml@main
    with:
      appName: review-$GITHUB_REF_NAME_SLUG
      globalEnv: review
      helmfileDir: deploy
      kubeConfigSecret: ci/data/dev/kubeconfig/k8s-dev
      vaultRole: ci-dev
    secrets: inherit
  cleanup_docker_image:
    uses: blockscout/actions/.github/workflows/cleanup_docker.yaml@main
    with:
      dockerImage: review-$GITHUB_REF_NAME_SLUG
    secrets: inherit
